[NEAT-818] Fix classic graph read operation (#1047)
# Description

TypeError: AssetsAPI.retrieve_multiple() got an unexpected keyword
argument 'id error when running
neat.read.cdf.classic.graph(root_asset_external_id=xxx,
identifier="externalId")

## Bump

- [x] Patch
- [ ] Minor
- [ ] Skip

## Changelog
### Fixed

- Fixed Assets API call to use the correct parameter `ids` instead of
`id`