🐛 DMS Equals filter on property (#1026)
# Description

See changelog below.

## Bump

- [x] Patch
- [ ] Minor
- [ ] Skip

## Changelog
### Fixed

- Reading a data model with a view with an equals filter on a property
no longer raises a `AttributeError: 'str' object has no attribute 'get'`
error.